apiVersion: v1
kind: Service
metadata:
 name: user-service-http
spec:
 selector:
  name: user-service
 type: NodePort
 ports:
  - protocol: TCP
    port: 10086
    targetPort: 10086
    nodePort: 30036
    name: user-service-tcp
